version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    steps:
      - checkout
      - run:
          name: Create google-services.json
          - echo $DT_ENV_GOOGLE_SERVICES_JSON_BASE64 | base64 --decode --ignore-garbage > ${HOME}/${CIRCLE_PROJECT_REPONAME}/app/google-services.json
      - restore_cache: # キャッシュをリストア
          key: jars-{{checksum "build.gradle"}}-{{checksum "app/build.gradle"}}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache: # キャッシュを保存
          paths:
            - ~/.gradle
          key: jars-{{checksum "build.gradle"}}-{{checksum "app/build.gradle"}}
      - run:
          name: Run Compile
          command: ./gradlew assembleDebug
      - run:
          name: Run Inspection
          command: ./gradlew lint
      - run:
          name: Run Test
          command: ./gradlew test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - run:
          name: Run Jacoco
          command: ./gradlew jacocoTestReport
      - run:
          name: Run Save coverrage
          command: |
              curl -s https://codecov.io/bash > .codecov
              chmod +x .codecov
              ./.codecov
      - run:
          name: Run Deploy
          command: |
              DEPLOYGATE_API_TOKEN=$DT_ENV_DEPLOYGATE_API_TOKEN \
              DEPLOYGATE_USER_NAME=$DT_ENV_DEPLOYGATE_USER_NAME \
              DEPLOYGATE_MESSAGE="for developpers" \
              ./gradlew uploadDeployGateDebug
