version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    steps:
      - checkout
      - restore_cache: # キャッシュをリストア
          key: jars-{{checksum "build.gradle"}}-{{checksum "app/build.gradle"}}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache: # キャッシュを保存
          paths:
            - ~/.gradle
          key: jars-{{checksum "build.gradle"}}-{{checksum "app/build.gradle"}}
      - run:
          name: Run Compile
          command: ./gradlew assembleDebug
      - run:
          name: Run Inspection
          command: ./gradlew lint
      - run:
          name: Run Test
          command: ./gradlew test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - run:
          name: Run Jacoco
          command: ./gradlew jacocoTestReport
      - run:
          name: Run Save coverrage
          command: |
              curl -s https://codecov.io/bash > .codecov
              chmod +x .codecov
              ./.codecov
